services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://database-2.c528io8smt7e.ap-northeast-2.rds.amazonaws.com:3306/gbjs
      - SPRING_DATASOURCE_USERNAME=gbjsuser
      - SPRING_DATASOURCE_PASSWORD=gbjs1234!!
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - gbjs-network

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - gbjs-network

networks:
  gbjs-network:
    driver: bridge

volumes:
  redis-data:
