version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}
      - SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
      - SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      - SPRING_REDIS_HOST=${{ secrets.SPRING_REDIS_HOST }}
    depends_on:
      - mysql
      - redis
    networks:
      - kbjs-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
      - MYSQL_USER=${{ secrets.MYSQL_USER }}
      - MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
      - MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - kbjs-network

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - kbjs-network

networks:
  kbjs-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
