# 공용 Compose 파일 (Blue/Green 앱 컨테이너와 관계없는 공용 서비스)
# Redis, Qdrant, Dozzle 등 공용으로 사용되는 stateful service 정의
services:
  redis:
    image: redis:7.2-alpine
    expose:
      - "6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASS}
    command: [ "redis-server", "--requirepass", "${REDIS_PASS}" ]
    volumes:
      - redis-data:/data
    networks:
      - gbjs-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASS}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  dozzle:
    image: amir20/dozzle:latest
    ports:
      - "9999:8080"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gbjs-network
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.12.3
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - gbjs-network
    restart: unless-stopped

networks:
  gbjs-network:
    driver: bridge

volumes:
  redis-data:
  qdrant-data:
