# Green 환경용 앱 컨테이너 Compose 파일
services:
  app-blue:
    image: unijuni/gbjs:latest
    container_name: gbjs-app-green
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE:-dev}
      SPRING_DATASOURCE_URL: jdbc:mysql://database-2.c528io8smt7e.ap-northeast-2.rds.amazonaws.com/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_REDIS_HOST: redis
    command: [ "java", "-jar", "app.jar" ]
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - gbjs-network
    restart: unless-stopped

networks:
  gbjs-network:
    external: false